# -*- coding: utf-8 -*-
"""MLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyTBdJc6LWDbhVfKYW5ECKzTYGGDG-fe
"""

# =========================================================
# LEGAL DOCUMENT / IPC SECTION CLASSIFICATION PROJECT
# USING NAIVE BAYES CLASSIFIER
# Categories:
# Civil, Criminal, Corporate
# =========================================================

# STEP 1: Import Required Libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline

# =========================================================
# STEP 2: Create Dataset
# =========================================================

data = {
    "text": [

        # Criminal
        "Whoever commits murder shall be punished",
        "The accused committed robbery and theft",
        "Kidnapping and criminal assault case",
        "Fraud and cheating under IPC section",
        "Punishment for attempted murder",

        # Civil
        "Property dispute between two families",
        "Land ownership disagreement case",
        "Divorce and family settlement issue",
        "Civil rights violation petition",
        "Compensation claim for property damage",

        # Corporate
        "Company violated shareholder agreement",
        "Corporate tax fraud investigation",
        "Business contract breach case",
        "Illegal activities in private company",
        "Financial audit of corporation"

    ],

    "category": [

        "Criminal",
        "Criminal",
        "Criminal",
        "Criminal",
        "Criminal",

        "Civil",
        "Civil",
        "Civil",
        "Civil",
        "Civil",

        "Corporate",
        "Corporate",
        "Corporate",
        "Corporate",
        "Corporate"
    ]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# =========================================================
# STEP 3: Split Dataset
# =========================================================

X = df["text"]
y = df["category"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================================================
# STEP 4: Create ML Pipeline
# TF-IDF + Naive Bayes
# =========================================================

model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", MultinomialNB())
])

# =========================================================
# STEP 5: Train Model
# =========================================================

model.fit(X_train, y_train)

# =========================================================
# STEP 6: Test Model
# =========================================================

y_pred = model.predict(X_test)

# =========================================================
# STEP 7: Accuracy
# =========================================================

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# =========================================================
# STEP 8: Predict New Legal Text
# =========================================================

new_case = [
    "The company misused shareholder funds"
]

prediction = model.predict(new_case)

print("\nPredicted Category:", prediction[0])

# =========================================================
# END OF PROJECT
# =========================================================

# =========================================================
# LEGAL DOCUMENT CLASSIFICATION SYSTEM
# GOOGLE COLAB VERSION
# Upload Document and Classify
# =========================================================

# =========================================================
# STEP 1: Install Required Libraries
# =========================================================

!pip install pandas scikit-learn

# =========================================================
# STEP 2: Import Libraries
# =========================================================

import pandas as pd
from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# =========================================================
# STEP 3: Upload Dataset CSV File
# =========================================================

print("UPLOAD legal_documents.csv FILE")

uploaded = files.upload()

# Read dataset
df = pd.read_csv("legal_documents.csv")

# Display dataset
print("\nDATASET LOADED SUCCESSFULLY\n")
print(df.head())

# =========================================================
# STEP 4: Prepare Data
# =========================================================

X = df["text"]
y = df["category"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================================================
# STEP 5: Create Machine Learning Model
# =========================================================

model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", MultinomialNB())
])

# Train model
model.fit(X_train, y_train)

print("\nMODEL TRAINED SUCCESSFULLY")

# =========================================================
# STEP 6: Check Accuracy
# =========================================================

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nMODEL ACCURACY:", accuracy)

# =========================================================
# STEP 7: Upload Legal Document
# =========================================================

print("\nUPLOAD samples.txt FILE")

uploaded_doc = files.upload()

# Get uploaded filename
filename = list(uploaded_doc.keys())[0]

# Read uploaded text file
with open(filename, "r", encoding="utf-8") as file:
    document_text = file.read()

# Display uploaded document
print("\nDOCUMENT CONTENT:\n")
print(document_text)

# =========================================================
# STEP 8: Predict Category
# =========================================================

prediction = model.predict([document_text])

print("\n===================================")
print("PREDICTED CATEGORY:", prediction[0])
print("===================================")



import streamlit as st
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# =========================
# TRAINING DATA
# =========================

texts = [
    "Whoever commits murder shall be punished",
    "The accused committed robbery and theft",
    "Kidnapping and criminal assault case",
    "Fraud and cheating under IPC section",
    "Punishment for attempted murder",

    "Property dispute between two families",
    "Land ownership disagreement case",
    "Divorce and family settlement issue",
    "Civil rights violation petition",
    "Compensation claim for property damage",

    "Company violated shareholder agreement",
    "Corporate tax fraud investigation",
    "Business contract breach case",
    "Illegal activities in private company",
    "Financial audit of corporation"
]

labels = [
    "Criminal",
    "Criminal",
    "Criminal",
    "Criminal",
    "Criminal",

    "Civil",
    "Civil",
    "Civil",
    "Civil",
    "Civil",

    "Corporate",
    "Corporate",
    "Corporate",
    "Corporate",
    "Corporate"
]

# =========================
# MODEL TRAINING
# =========================

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(texts)

model = MultinomialNB()

model.fit(X, labels)

# =========================
# UI DESIGN
# =========================

st.set_page_config(
    page_title="Legal Document Classifier",
    page_icon="⚖️",
    layout="centered"
)

st.title("⚖️ Legal Document Classification")

st.write(
    "Enter legal document text and predict its category."
)

user_input = st.text_area(
    "Enter Legal Text",
    height=200
)

if st.button("Predict Category"):

    if user_input.strip() != "":

        transformed_text = vectorizer.transform([user_input])

        prediction = model.predict(transformed_text)

        st.success(f"Predicted Category: {prediction[0]}")

    else:
        st.warning("Please enter some legal text.")